// Package winclient provides an SSH client wrapper.
//
// Generated by KDust bootstrap task.
package winclient

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"net"
	"strconv"
	"strings"
	"time"
	"unicode/utf16"

	"golang.org/x/crypto/ssh"
)

// Client wraps an SSH connection and exposes helpers to run PowerShell
// scripts against the configured Windows host (via its OpenSSH Server,
// with PowerShell as the invoked command).
type Client struct {
	cfg     Config
	sshCfg  *ssh.ClientConfig
	address string
}

// New creates and validates a new SSH Client from the given Config. It does
// not open a network connection until the first RunPowerShell call.
func New(cfg Config) (*Client, error) {
	if cfg.Host == "" {
		return nil, fmt.Errorf("winclient: host is required")
	}
	if cfg.Username == "" {
		return nil, fmt.Errorf("winclient: username is required")
	}
	if cfg.Password == "" {
		return nil, fmt.Errorf("winclient: password is required")
	}
	if cfg.Port == 0 {
		cfg.Port = 22
	}
	if cfg.Timeout == 0 {
		cfg.Timeout = 30 * time.Second
	}

	sshCfg := &ssh.ClientConfig{
		User:    cfg.Username,
		Auth:    []ssh.AuthMethod{ssh.Password(cfg.Password)},
		Timeout: cfg.Timeout,
		// Host key verification is intentionally not performed: this provider
		// targets short-lived automation hosts with no established
		// known_hosts baseline, mirroring the trust model of the previous
		// SSH transport (which had no host identity check either).
		HostKeyCallback: ssh.InsecureIgnoreHostKey(), //nolint:gosec // see comment above
	}

	return &Client{
		cfg:     cfg,
		sshCfg:  sshCfg,
		address: net.JoinHostPort(cfg.Host, strconv.Itoa(cfg.Port)),
	}, nil
}

// Config returns a shallow copy of the client configuration (password
// included — callers must not log it).
func (c *Client) Config() Config { return c.cfg }

// RunPowerShell executes the given PowerShell script on the remote host and
// returns its stdout and stderr. It honours the provided context for
// cancellation.
//
// The script is not placed on the command line: only a fixed bootstrap is
// passed via -EncodedCommand, and the real script (UTF-16LE base64) is streamed
// on stdin, so the command line stays a constant ~600 chars regardless of script
// size. This keeps us under Windows' ~8191-char command-line limit (#39) while
// preserving exact UTF-16LE fidelity for non-ASCII values.
func (c *Client) RunPowerShell(ctx context.Context, script string) (string, string, error) {
	return c.run(ctx, composeStdin(script, ""))
}

// RunPowerShellWithInput executes the given PowerShell script with the supplied
// stdin string piped to the process. This allows sensitive data (e.g. passwords)
// to be injected via stdin rather than the script body, so the plaintext never
// appears in the encoded command or SSH session logs.
//
// Transport matches RunPowerShell: a fixed bootstrap decodes the real script
// from the first stdin line, then the script itself reads the caller's input
// from the remainder via [Console]::In.ReadLine() / ReadToEnd().
func (c *Client) RunPowerShellWithInput(ctx context.Context, script, stdin string) (string, string, error) {
	return c.run(ctx, composeStdin(script, stdin))
}

// run dials a fresh SSH connection, opens a session running the fixed
// bootstrap command with stdinReader piped in, and returns its stdout/stderr.
func (c *Client) run(ctx context.Context, stdinReader io.Reader) (string, string, error) {
	if c == nil || c.sshCfg == nil {
		return "", "", fmt.Errorf("winclient: nil client")
	}

	client, err := c.dial(ctx)
	if err != nil {
		return "", "", err
	}
	defer func() { _ = client.Close() }()

	session, err := client.NewSession()
	if err != nil {
		return "", "", fmt.Errorf("winclient: new ssh session: %w", err)
	}
	defer func() { _ = session.Close() }()

	var stdout, stderr bytes.Buffer
	session.Stdout = &stdout
	session.Stderr = &stderr
	session.Stdin = stdinReader

	done := make(chan error, 1)
	go func() { done <- session.Run(bootstrapCommand()) }()

	select {
	case <-ctx.Done():
		_ = session.Close()
		return stdout.String(), stderr.String(), ctx.Err()
	case runErr := <-done:
		if runErr != nil {
			var exitErr *ssh.ExitError
			if errors.As(runErr, &exitErr) {
				return stdout.String(), stderr.String(), fmt.Errorf("winclient: powershell exited with code %d", exitErr.ExitStatus())
			}
			return stdout.String(), stderr.String(), fmt.Errorf("winclient: powershell run: %w", runErr)
		}
		return stdout.String(), stderr.String(), nil
	}
}

// dial opens a new SSH connection to the configured host, honouring ctx for
// cancellation of the underlying TCP dial.
func (c *Client) dial(ctx context.Context) (*ssh.Client, error) {
	d := net.Dialer{Timeout: c.cfg.Timeout}
	conn, err := d.DialContext(ctx, "tcp", c.address)
	if err != nil {
		return nil, fmt.Errorf("winclient: dial: %w", err)
	}
	sshConn, chans, reqs, err := ssh.NewClientConn(conn, c.address, c.sshCfg)
	if err != nil {
		_ = conn.Close()
		return nil, fmt.Errorf("winclient: ssh handshake: %w", err)
	}
	return ssh.NewClient(sshConn, chans, reqs), nil
}

// psBootstrap is the constant script passed via -EncodedCommand. It reads a
// single base64 (UTF-16LE) line from stdin, decodes it to the real script, and
// executes it. Because the large payload travels on stdin rather than the
// command line, the command line stays a fixed ~600 chars — well under Windows'
// ~8191-char limit (#39). Errors are surfaced by the invoked script's own JSON
// envelope; a failed decode throws (ErrorActionPreference=Stop) and exits non-zero.
const psBootstrap = `$ErrorActionPreference='Stop'
$b64=[Console]::In.ReadLine()
$code=[Text.Encoding]::Unicode.GetString([Convert]::FromBase64String($b64))
& ([ScriptBlock]::Create($code))`

// bootstrapCommand builds the fixed powershell.exe invocation. It does not
// depend on the script being run, so its length is constant.
func bootstrapCommand() string {
	return fmt.Sprintf("powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand %s", encodePowerShell(psBootstrap))
}

// composeStdin lays out the stdin stream the bootstrap expects: the base64
// (UTF-16LE) script as the first line, then any caller-supplied input as the
// remainder. The bootstrap consumes the first line; the script then reads input
// from the rest via [Console]::In.ReadLine() / ReadToEnd(). base64 uses the
// standard alphabet (no newlines), so it is always exactly one line.
func composeStdin(script, input string) io.Reader {
	return strings.NewReader(encodePowerShell(script) + "\n" + input)
}

// encodePowerShell encodes a script as UTF-16LE base64, matching the
// format expected by powershell.exe -EncodedCommand.
func encodePowerShell(script string) string {
	runes := utf16.Encode([]rune(script))
	buf := new(bytes.Buffer)
	_ = binary.Write(buf, binary.LittleEndian, runes)
	return base64.StdEncoding.EncodeToString(buf.Bytes())
}
