// Package winclient provides a WinRM client wrapper.
//
// Generated by KDust bootstrap task.
package winclient

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"time"
	"unicode/utf16"

	"github.com/masterzen/winrm"
)

// Client wraps a WinRM session and exposes helpers to run PowerShell scripts
// against the configured Windows host.
type Client struct {
	cfg   Config
	winrm *winrm.Client
}

// New creates and validates a new WinRM Client from the given Config.
// It does not open a network connection until the first RunPowerShell call.
func New(cfg Config) (*Client, error) {
	if cfg.Host == "" {
		return nil, fmt.Errorf("winclient: host is required")
	}
	if cfg.Username == "" {
		return nil, fmt.Errorf("winclient: username is required")
	}
	if cfg.Password == "" {
		return nil, fmt.Errorf("winclient: password is required")
	}
	if cfg.Port == 0 {
		if cfg.UseHTTPS {
			cfg.Port = 5986
		} else {
			cfg.Port = 5985
		}
	}
	if cfg.Timeout == 0 {
		cfg.Timeout = 30 * time.Second
	}
	if cfg.AuthType == "" {
		cfg.AuthType = "ntlm"
	}

	endpoint := winrm.NewEndpoint(cfg.Host, cfg.Port, cfg.UseHTTPS, cfg.Insecure, nil, nil, nil, cfg.Timeout)

	params := winrm.DefaultParameters
	params.Timeout = fmt.Sprintf("PT%.0fS", cfg.Timeout.Seconds())

	switch cfg.AuthType {
	case "ntlm":
		params.TransportDecorator = func() winrm.Transporter { return &winrm.ClientNTLM{} }
	case "basic":
		// default transporter (basic auth over HTTP(S))
	case "kerberos":
		return nil, fmt.Errorf("winclient: kerberos auth is not implemented yet")
	default:
		return nil, fmt.Errorf("winclient: unsupported auth_type %q", cfg.AuthType)
	}

	c, err := winrm.NewClientWithParameters(endpoint, cfg.Username, cfg.Password, params)
	if err != nil {
		return nil, fmt.Errorf("winclient: create winrm client: %w", err)
	}

	return &Client{cfg: cfg, winrm: c}, nil
}

// Config returns a shallow copy of the client configuration (password
// included — callers must not log it).
func (c *Client) Config() Config { return c.cfg }

// RunPowerShell executes the given PowerShell script on the remote host
// using -EncodedCommand (UTF-16LE base64) and returns its stdout and stderr.
// It honours the provided context for cancellation.
func (c *Client) RunPowerShell(ctx context.Context, script string) (string, string, error) {
	if c == nil || c.winrm == nil {
		return "", "", fmt.Errorf("winclient: nil client")
	}

	encoded := encodePowerShell(script)
	cmd := fmt.Sprintf("powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand %s", encoded)

	var stdout, stderr bytes.Buffer
	type result struct {
		code int
		err  error
	}
	done := make(chan result, 1)
	go func() {
		code, err := c.winrm.RunWithContextWithInput(ctx, cmd, &stdout, &stderr, nil)
		done <- result{code: code, err: err}
	}()

	select {
	case <-ctx.Done():
		return stdout.String(), stderr.String(), ctx.Err()
	case r := <-done:
		if r.err != nil {
			return stdout.String(), stderr.String(), fmt.Errorf("winclient: powershell run: %w", r.err)
		}
		if r.code != 0 {
			return stdout.String(), stderr.String(), fmt.Errorf("winclient: powershell exited with code %d", r.code)
		}
		return stdout.String(), stderr.String(), nil
	}
}

// encodePowerShell encodes a script as UTF-16LE base64, matching the
// format expected by powershell.exe -EncodedCommand.
func encodePowerShell(script string) string {
	runes := utf16.Encode([]rune(script))
	buf := new(bytes.Buffer)
	_ = binary.Write(buf, binary.LittleEndian, runes)
	return base64.StdEncoding.EncodeToString(buf.Bytes())
}
