// Package winclient provides an SSH client wrapper.
//
// Generated by KDust bootstrap task.
package winclient

import (
	"bufio"
	"bytes"
	"context"
	"encoding/base64"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"net"
	"strconv"
	"sync"
	"time"
	"unicode/utf16"

	"golang.org/x/crypto/ssh"
)

// Client wraps an SSH connection and exposes helpers to run PowerShell
// scripts against the configured Windows host (via its OpenSSH Server,
// with PowerShell as the invoked command).
//
// A Client keeps at most one persistent PowerShell session open at a time
// (issue #81): the first RunPowerShell/RunPowerShellWithInput call dials and
// starts it, later calls reuse it, and a broken session is transparently
// re-established. Calls are serialised by mu — the SSH session's stdin/
// stdout/stderr are a single shared, ordered stream, so two calls cannot
// safely interleave on it.
type Client struct {
	cfg     Config
	sshCfg  *ssh.ClientConfig
	address string

	mu      sync.Mutex
	session *persistentSession
}

// New creates and validates a new SSH Client from the given Config. It does
// not open a network connection until the first RunPowerShell call.
func New(cfg Config) (*Client, error) {
	if cfg.Host == "" {
		return nil, fmt.Errorf("winclient: host is required")
	}
	if cfg.Username == "" {
		return nil, fmt.Errorf("winclient: username is required")
	}
	if cfg.Port == 0 {
		cfg.Port = 22
	}
	if cfg.Timeout == 0 {
		cfg.Timeout = 30 * time.Second
	}

	auth, err := buildAuthMethods(cfg)
	if err != nil {
		return nil, err
	}
	hostKeys, err := hostKeyCallback(cfg)
	if err != nil {
		return nil, err
	}

	sshCfg := &ssh.ClientConfig{
		User:            cfg.Username,
		Auth:            auth,
		Timeout:         cfg.Timeout,
		HostKeyCallback: hostKeys,
	}

	return &Client{
		cfg:     cfg,
		sshCfg:  sshCfg,
		address: net.JoinHostPort(cfg.Host, strconv.Itoa(cfg.Port)),
	}, nil
}

// Config returns a shallow copy of the client configuration (password
// included — callers must not log it).
func (c *Client) Config() Config { return c.cfg }

// Close tears down the persistent PowerShell session, if one is open. Safe
// to call on a Client that never ran a command, and safe to call more than
// once.
func (c *Client) Close() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.session == nil {
		return nil
	}
	err := c.session.Close()
	c.session = nil
	return err
}

// RunPowerShell executes the given PowerShell script on the remote host and
// returns its stdout and stderr. It honours the provided context for
// cancellation.
//
// The script is not placed on the command line: only a fixed bootstrap is
// passed via -EncodedCommand, and the real script (UTF-16LE base64) is
// streamed on stdin, so the command line stays a constant ~600 chars
// regardless of script size. This keeps us under Windows' ~8191-char
// command-line limit (#39) while preserving exact UTF-16LE fidelity for
// non-ASCII values.
func (c *Client) RunPowerShell(ctx context.Context, script string) (string, string, error) {
	return c.run(ctx, script, "")
}

// RunPowerShellWithInput executes the given PowerShell script with the
// supplied stdin string piped to the process. This allows sensitive data
// (e.g. passwords) to be injected via stdin rather than the script body, so
// the plaintext never appears in the encoded command or SSH session logs.
func (c *Client) RunPowerShellWithInput(ctx context.Context, script, stdin string) (string, string, error) {
	return c.run(ctx, script, stdin)
}

// run sends one request to the persistent PowerShell session, establishing
// it first if needed, and retries exactly once against a freshly
// re-established session if the existing one turns out to be dead. That
// keeps a stale session (remote crash, dropped TCP connection, idle
// timeout) from permanently failing every subsequent call.
func (c *Client) run(ctx context.Context, script, secret string) (string, string, error) {
	if c == nil {
		return "", "", fmt.Errorf("winclient: nil client")
	}

	c.mu.Lock()
	defer c.mu.Unlock()

	if c.session == nil {
		sess, err := newPersistentSession(ctx, c)
		if err != nil {
			return "", "", err
		}
		c.session = sess
	}

	stdout, stderr, err := c.session.run(ctx, script, secret)
	if !isSessionBroken(err) {
		return stdout, stderr, err
	}

	_ = c.session.Close()
	c.session = nil

	sess, dialErr := newPersistentSession(ctx, c)
	if dialErr != nil {
		return stdout, stderr, fmt.Errorf("winclient: session dropped and could not be re-established: %w (original error: %v)", dialErr, err)
	}
	c.session = sess
	return c.session.run(ctx, script, secret)
}

// isSessionBroken reports whether err indicates the persistent session
// itself is unusable (closed pipe, dropped connection, protocol framing
// lost) as opposed to the script it just ran having failed on the remote
// side, which readReplResponse already turns into a normal (nil-error)
// result carrying status information in stdout/stderr.
func isSessionBroken(err error) bool {
	return err != nil
}

// dial opens a new SSH connection to the configured host, honouring ctx for
// cancellation of the underlying TCP dial.
func (c *Client) dial(ctx context.Context) (*ssh.Client, error) {
	d := net.Dialer{Timeout: c.cfg.Timeout}
	conn, err := d.DialContext(ctx, "tcp", c.address)
	if err != nil {
		return nil, fmt.Errorf("winclient: dial: %w", err)
	}
	sshConn, chans, reqs, err := ssh.NewClientConn(conn, c.address, c.sshCfg)
	if err != nil {
		_ = conn.Close()
		return nil, fmt.Errorf("winclient: ssh handshake: %w", err)
	}
	return ssh.NewClient(sshConn, chans, reqs), nil
}

// persistentSession wraps one SSH connection running the REPL bootstrap. It
// is not safe for concurrent use; Client.mu is what makes that safe in
// practice.
type persistentSession struct {
	sshClient *ssh.Client
	session   *ssh.Session
	stdin     io.WriteCloser
	stdout    *bufio.Reader
	stderr    *bufio.Reader
	marker    string
}

// newPersistentSession dials, starts the REPL bootstrap and waits for its
// ready handshake before handing the session back.
func newPersistentSession(ctx context.Context, c *Client) (*persistentSession, error) {
	sshClient, err := c.dial(ctx)
	if err != nil {
		return nil, err
	}

	session, err := sshClient.NewSession()
	if err != nil {
		_ = sshClient.Close()
		return nil, fmt.Errorf("winclient: new ssh session: %w", err)
	}

	stdin, err := session.StdinPipe()
	if err != nil {
		_ = session.Close()
		_ = sshClient.Close()
		return nil, fmt.Errorf("winclient: stdin pipe: %w", err)
	}
	stdoutPipe, err := session.StdoutPipe()
	if err != nil {
		_ = session.Close()
		_ = sshClient.Close()
		return nil, fmt.Errorf("winclient: stdout pipe: %w", err)
	}
	stderrPipe, err := session.StderrPipe()
	if err != nil {
		_ = session.Close()
		_ = sshClient.Close()
		return nil, fmt.Errorf("winclient: stderr pipe: %w", err)
	}

	if err := session.Start(replBootstrapCommand()); err != nil {
		_ = session.Close()
		_ = sshClient.Close()
		return nil, fmt.Errorf("winclient: start powershell REPL: %w", err)
	}

	ps := &persistentSession{
		sshClient: sshClient,
		session:   session,
		stdin:     stdin,
		stdout:    bufio.NewReader(stdoutPipe),
		stderr:    bufio.NewReader(stderrPipe),
	}

	type readyResult struct {
		marker string
		err    error
	}
	done := make(chan readyResult, 1)
	go func() {
		marker, err := readReplReady(ps.stdout)
		done <- readyResult{marker, err}
	}()

	select {
	case <-ctx.Done():
		_ = ps.Close()
		return nil, ctx.Err()
	case r := <-done:
		if r.err != nil {
			_ = ps.Close()
			return nil, r.err
		}
		ps.marker = r.marker
		return ps, nil
	}
}

// run sends one request and waits for its framed response, honouring ctx
// for cancellation. It returns a non-nil error only for transport/protocol
// failures; a script that raised an uncaught PowerShell error is reported
// through the returned stderr text plus a wrapped error identifying it as
// such, mirroring the old one-process-per-call non-zero exit behaviour
// closely enough that callers built around extractLastJSONLine keep working
// unmodified.
func (ps *persistentSession) run(ctx context.Context, script, secret string) (string, string, error) {
	type result struct {
		stdout, stderr string
		status         int
		err            error
	}
	done := make(chan result, 1)
	go func() {
		if _, err := io.WriteString(ps.stdin, encodeReplRequest(script, secret)); err != nil {
			done <- result{err: fmt.Errorf("winclient: write REPL request: %w", err)}
			return
		}
		stdout, stderr, status, err := readReplResponse(ps.stdout, ps.stderr)
		done <- result{stdout, stderr, status, err}
	}()

	select {
	case <-ctx.Done():
		_ = ps.Close()
		return "", "", ctx.Err()
	case r := <-done:
		if r.err != nil {
			return r.stdout, r.stderr, r.err
		}
		if r.status != 0 {
			return r.stdout, r.stderr, fmt.Errorf("winclient: powershell script raised an uncaught error")
		}
		return r.stdout, r.stderr, nil
	}
}

// Close ends the REPL loop by closing stdin (read as EOF by
// [Console]::In.ReadLine()) and tears down the SSH session and connection.
func (ps *persistentSession) Close() error {
	var errs []error
	if err := ps.stdin.Close(); err != nil {
		errs = append(errs, err)
	}
	if err := ps.session.Close(); err != nil && !errors.Is(err, io.EOF) {
		errs = append(errs, err)
	}
	if err := ps.sshClient.Close(); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// encodePowerShell encodes a script as UTF-16LE base64, matching the
// format expected by powershell.exe -EncodedCommand.
func encodePowerShell(script string) string {
	runes := utf16.Encode([]rune(script))
	buf := new(bytes.Buffer)
	_ = binary.Write(buf, binary.LittleEndian, runes)
	return base64.StdEncoding.EncodeToString(buf.Bytes())
}
