// Package winclient provides an SSH client wrapper used by the Terraform
// provider to execute PowerShell scripts against Windows hosts.
//
// Generated by KDust bootstrap task.
package winclient

import (
	"os"
	"time"
)

// Config holds connection settings for an SSH session. No credentials are
// ever hardcoded: values come from the provider block or environment.
type Config struct {
	Host     string
	Port     int
	Username string
	Password string
	Timeout  time.Duration
}

// Environment variable names used as fallback when provider attributes are
// unset.
const (
	EnvHost     = "WINDOWS_HOST"
	EnvUsername = "WINDOWS_USERNAME"
	EnvPassword = "WINDOWS_PASSWORD" //nolint:gosec // name of env var, not a secret
)

// ResolveFromEnv fills any empty field in cfg with the corresponding
// environment variable value, if set. It never logs secret values.
func ResolveFromEnv(cfg *Config) {
	if cfg.Host == "" {
		cfg.Host = os.Getenv(EnvHost)
	}
	if cfg.Username == "" {
		cfg.Username = os.Getenv(EnvUsername)
	}
	if cfg.Password == "" {
		cfg.Password = os.Getenv(EnvPassword)
	}
}
