# GNUmakefile for terraform-provider-windows
#
# Generated by KDust bootstrap task.

HOSTNAME ?= registry.terraform.io
NAMESPACE ?= ecritel
NAME ?= windows
BINARY = terraform-provider-$(NAME)
VERSION ?= 0.1.0
OS_ARCH ?= linux_amd64

.PHONY: build test testacc lint fmt docs install clean

build:
	go install ./...

test:
	go test -short ./... -timeout 30s

testacc:
	TF_ACC=1 go test ./... -v -timeout 120m

lint:
	golangci-lint run

fmt:
	gofmt -s -w .
	@command -v terraform >/dev/null 2>&1 && terraform fmt -recursive examples/ || echo "terraform not installed, skipping examples/ fmt"

docs:
	go generate ./...

clean:
	rm -f $(BINARY)
