// Package main is the entry point for the terraform-provider-windows plugin.
//
// Generated by KDust bootstrap task.
package main

import (
	"context"
	"flag"
	"log"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"

	"github.com/kfrlabs/terraform-provider-windows/internal/provider"
)

// providerAddress is the Terraform Registry address of this provider.
const providerAddress = "registry.terraform.io/kfrlabs/windows"

// version is injected at build time via -ldflags.
var version = "dev"

func main() {
	var debug bool
	flag.BoolVar(&debug, "debug", false, "set to true to run the provider with support for debuggers like delve")
	flag.Parse()

	opts := providerserver.ServeOpts{
		Address: providerAddress,
		Debug:   debug,
	}

	if err := providerserver.Serve(context.Background(), provider.New(version), opts); err != nil {
		log.Fatal(err.Error())
	}
}
