// Package provider implements the root Terraform provider for Windows.
//
// Generated by KDust bootstrap task.
package provider

import "github.com/hashicorp/terraform-plugin-framework/path"

// pathAttr returns a path.Path targeting a root attribute of the provider
// configuration block. It exists to keep diagnostic call sites terse.
func pathAttr(name string) path.Path { return path.Root(name) }
