// Package provider implements the root Terraform provider for Windows.
//
// Generated by KDust bootstrap task.
package provider

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/kfrlabs/terraform-provider-windows/internal/winclient"
)

// Ensure the implementation satisfies the expected interfaces.
var _ provider.Provider = (*windowsProvider)(nil)

// windowsProvider is the concrete provider implementation.
type windowsProvider struct {
	version string
}

// New returns a constructor suitable for providerserver.Serve.
func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &windowsProvider{version: version}
	}
}

// providerModel mirrors the provider configuration block.
type providerModel struct {
	Host     types.String `tfsdk:"host"`
	Port     types.Int64  `tfsdk:"port"`
	Username types.String `tfsdk:"username"`
	Password types.String `tfsdk:"password"`
	Timeout  types.String `tfsdk:"timeout"`

	PrivateKey           types.String `tfsdk:"private_key"`
	PrivateKeyPath       types.String `tfsdk:"private_key_path"`
	PrivateKeyPassphrase types.String `tfsdk:"private_key_passphrase"`
	UseAgent             types.Bool   `tfsdk:"use_agent"`

	KnownHostsPath        types.String `tfsdk:"known_hosts_path"`
	HostKey               types.String `tfsdk:"host_key"`
	InsecureIgnoreHostKey types.Bool   `tfsdk:"insecure_ignore_host_key"`
}

// Metadata sets the provider type name and version.
func (p *windowsProvider) Metadata(_ context.Context, _ provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "windows"
	resp.Version = p.version
}

// Schema defines the provider configuration schema.
func (p *windowsProvider) Schema(_ context.Context, _ provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The windows provider manages Windows resources over SSH " +
			"(the target host's OpenSSH Server, invoking PowerShell). It supports " +
			"public-key, ssh-agent and password authentication, and verifies the " +
			"server's host key by default.",
		Attributes: map[string]schema.Attribute{
			"host": schema.StringAttribute{
				Description: "Hostname or IP address of the target Windows host. May also be set via WINDOWS_HOST.",
				Optional:    true,
			},
			"port": schema.Int64Attribute{
				Description: "SSH port. Defaults to 22. May also be set via WINDOWS_PORT.",
				Optional:    true,
			},
			"username": schema.StringAttribute{
				Description: "SSH username. May also be set via WINDOWS_USERNAME.",
				Optional:    true,
			},
			"password": schema.StringAttribute{
				Description: "SSH password. May also be set via WINDOWS_PASSWORD. Prefer key-based " +
					"authentication where possible.",
				Optional:  true,
				Sensitive: true,
			},
			"timeout": schema.StringAttribute{
				Description: "Timeout for establishing the SSH connection (TCP dial plus handshake), as a " +
					"Go duration string (e.g. 30s, 2m). Default: 30s. This does NOT bound how long a " +
					"PowerShell operation may run: use the per-resource timeouts block for that.",
				Optional: true,
			},
			"private_key": schema.StringAttribute{
				Description: "PEM-encoded SSH private key used for public-key authentication. " +
					"Mutually exclusive with private_key_path. May also be set via WINDOWS_PRIVATE_KEY.",
				Optional:  true,
				Sensitive: true,
			},
			"private_key_path": schema.StringAttribute{
				Description: "Path to a PEM-encoded SSH private key. A leading '~' is expanded to the " +
					"current user's home directory. Mutually exclusive with private_key. May also be " +
					"set via WINDOWS_PRIVATE_KEY_PATH.",
				Optional: true,
			},
			"private_key_passphrase": schema.StringAttribute{
				Description: "Passphrase decrypting the private key, when it is protected. May also be " +
					"set via WINDOWS_PRIVATE_KEY_PASSPHRASE.",
				Optional:  true,
				Sensitive: true,
			},
			"use_agent": schema.BoolAttribute{
				Description: "Whether to authenticate through the ssh-agent advertised by SSH_AUTH_SOCK. " +
					"When unset, the agent is used if SSH_AUTH_SOCK is present. Unavailable when " +
					"Terraform itself runs on Windows, where the agent is a named pipe rather than a " +
					"Unix socket: use private_key_path there. May also be set via WINDOWS_USE_AGENT.",
				Optional: true,
			},
			"known_hosts_path": schema.StringAttribute{
				Description: "OpenSSH known_hosts file used to verify the server's host key. Defaults to " +
					"~/.ssh/known_hosts. Mutually exclusive with host_key. May also be set via " +
					"WINDOWS_KNOWN_HOSTS.",
				Optional: true,
			},
			"host_key": schema.StringAttribute{
				Description: "The server's expected public key in authorized_keys form " +
					"(e.g. 'ssh-ed25519 AAAAC3Nz...'), pinned directly instead of consulting a " +
					"known_hosts file. Useful in CI or Terraform Cloud, where no known_hosts exists. " +
					"Mutually exclusive with known_hosts_path. May also be set via WINDOWS_HOST_KEY.",
				Optional: true,
			},
			"insecure_ignore_host_key": schema.BoolAttribute{
				Description: "Disable host key verification entirely. This exposes every connection to " +
					"man-in-the-middle interception and should only be used against disposable hosts on " +
					"a trusted network. Defaults to false. May also be set via " +
					"WINDOWS_INSECURE_IGNORE_HOST_KEY.",
				Optional: true,
			},
		},
	}
}

// Configure validates the provider configuration, applies environment
// fallbacks, and constructs a shared SSH client made available to all
// resources and data sources via resp.ResourceData / resp.DataSourceData.
func (p *windowsProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data providerModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if data.Host.IsUnknown() {
		resp.Diagnostics.AddAttributeError(
			pathAttr("host"),
			"Unknown Windows host",
			"The provider cannot create the SSH client because the host is unknown at plan time.",
		)
	}
	if data.Username.IsUnknown() {
		resp.Diagnostics.AddAttributeError(
			pathAttr("username"),
			"Unknown Windows username",
			"The provider cannot create the SSH client because the username is unknown at plan time.",
		)
	}
	// Every remaining connection attribute must be known too. An unknown value
	// would otherwise collapse to the zero value — silently dialing port 22, or
	// silently turning host key verification back on or off — which is worse
	// than refusing to configure.
	for name, value := range map[string]attr.Value{
		"password":                 data.Password,
		"private_key":              data.PrivateKey,
		"private_key_path":         data.PrivateKeyPath,
		"private_key_passphrase":   data.PrivateKeyPassphrase,
		"host_key":                 data.HostKey,
		"known_hosts_path":         data.KnownHostsPath,
		"port":                     data.Port,
		"timeout":                  data.Timeout,
		"use_agent":                data.UseAgent,
		"insecure_ignore_host_key": data.InsecureIgnoreHostKey,
	} {
		if value.IsUnknown() {
			resp.Diagnostics.AddAttributeError(
				pathAttr(name),
				"Unknown provider configuration",
				fmt.Sprintf("The provider cannot create the SSH client because %q is unknown at plan time.", name),
			)
		}
	}
	if resp.Diagnostics.HasError() {
		return
	}

	// A null bool means "not configured", which the winclient layer
	// distinguishes from an explicit false via a nil pointer.
	var useAgent *bool
	if !data.UseAgent.IsNull() {
		v := data.UseAgent.ValueBool()
		useAgent = &v
	}

	cfg := winclient.Config{
		Host:                  data.Host.ValueString(),
		Port:                  int(data.Port.ValueInt64()),
		Username:              data.Username.ValueString(),
		Password:              data.Password.ValueString(),
		PrivateKey:            data.PrivateKey.ValueString(),
		PrivateKeyPath:        data.PrivateKeyPath.ValueString(),
		PrivateKeyPassphrase:  data.PrivateKeyPassphrase.ValueString(),
		UseAgent:              useAgent,
		KnownHostsPath:        data.KnownHostsPath.ValueString(),
		HostKey:               data.HostKey.ValueString(),
		InsecureIgnoreHostKey: data.InsecureIgnoreHostKey.ValueBool(),
	}

	winclient.ResolveFromEnv(&cfg)

	if cfg.Host == "" {
		resp.Diagnostics.AddAttributeError(pathAttr("host"), "Missing Windows host",
			"Set provider attribute 'host' or environment variable WINDOWS_HOST.")
	}
	if cfg.Username == "" {
		resp.Diagnostics.AddAttributeError(pathAttr("username"), "Missing Windows username",
			"Set provider attribute 'username' or environment variable WINDOWS_USERNAME.")
	}
	if resp.Diagnostics.HasError() {
		return
	}

	// Losing host identity verification is silent and total: the connection
	// still succeeds, it just no longer proves who answered. Surface it on
	// every plan and apply rather than only in the docs.
	if cfg.InsecureIgnoreHostKey {
		resp.Diagnostics.AddAttributeWarning(
			pathAttr("insecure_ignore_host_key"),
			"SSH host key verification is disabled",
			"The provider will accept any host key presented by "+cfg.Host+", so this connection "+
				"cannot detect a man-in-the-middle. Credentials and PowerShell payloads may be "+
				"exposed to an impostor host. Remove 'insecure_ignore_host_key' and set 'host_key' "+
				"or 'known_hosts_path' instead.",
		)
	}

	timeoutStr := data.Timeout.ValueString()
	if timeoutStr == "" {
		timeoutStr = "30s"
	}
	d, err := time.ParseDuration(timeoutStr)
	if err != nil {
		resp.Diagnostics.AddAttributeError(pathAttr("timeout"), "Invalid timeout",
			fmt.Sprintf("Could not parse duration %q: %s", timeoutStr, err))
		return
	}
	cfg.Timeout = d

	client, err := winclient.New(cfg)
	if err != nil {
		resp.Diagnostics.AddError("Unable to create SSH client", err.Error())
		return
	}

	resp.ResourceData = client
	resp.DataSourceData = client
}

// Resources returns the set of resources implemented by this provider.
// The list is empty at bootstrap and filled in by follow-up KDust tasks.
func (p *windowsProvider) Resources(_ context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewWindowsEnvironmentVariableResource,
		NewWindowsFeatureResource,
		NewWindowsFirewallRuleResource,
		NewWindowsHostnameResource,
		NewWindowsLegacyPackageResource,
		NewWindowsLocalGroupResource,
		NewWindowsLocalGroupMemberResource,
		NewWindowsLocalUserResource,
		NewWindowsRegistryValueResource,
		NewWindowsScheduledTaskResource,
		NewWindowsServiceResource,
		NewWindowsWingetPackageResource,
	}
}

// DataSources returns the set of data sources implemented by this provider.
func (p *windowsProvider) DataSources(_ context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewWindowsEnvironmentVariableDataSource,
		NewWindowsFeatureDataSource,
		NewWindowsFirewallRuleDataSource,
		NewWindowsHostnameDataSource,
		NewWindowsLocalGroupDataSource,
		NewWindowsLocalGroupMemberDataSource,
		NewWindowsLocalUserDataSource,
		NewWindowsRegistryValueDataSource,
		NewWindowsScheduledTaskDataSource,
		NewWindowsServiceDataSource,
		NewWindowsWingetPackageDataSource,
	}
}
