// Package provider implements the root Terraform provider for Windows.
//
// Generated by KDust bootstrap task.
package provider

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/ecritel/terraform-provider-windows/internal/winclient"
)

// Ensure the implementation satisfies the expected interfaces.
var _ provider.Provider = (*windowsProvider)(nil)

// windowsProvider is the concrete provider implementation.
type windowsProvider struct {
	version string
}

// New returns a constructor suitable for providerserver.Serve.
func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &windowsProvider{version: version}
	}
}

// providerModel mirrors the provider configuration block.
type providerModel struct {
	Host     types.String `tfsdk:"host"`
	Port     types.Int64  `tfsdk:"port"`
	Username types.String `tfsdk:"username"`
	Password types.String `tfsdk:"password"`
	UseHTTPS types.Bool   `tfsdk:"use_https"`
	Insecure types.Bool   `tfsdk:"insecure"`
	AuthType types.String `tfsdk:"auth_type"`
	Timeout  types.String `tfsdk:"timeout"`
}

// Metadata sets the provider type name and version.
func (p *windowsProvider) Metadata(_ context.Context, _ provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "windows"
	resp.Version = p.version
}

// Schema defines the provider configuration schema.
func (p *windowsProvider) Schema(_ context.Context, _ provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "The windows provider manages Windows resources over WinRM.",
		Attributes: map[string]schema.Attribute{
			"host": schema.StringAttribute{
				Description: "Hostname or IP address of the target Windows host. May also be set via WINDOWS_HOST.",
				Optional:    true,
			},
			"port": schema.Int64Attribute{
				Description: "WinRM port (default 5985 for HTTP, 5986 for HTTPS).",
				Optional:    true,
			},
			"username": schema.StringAttribute{
				Description: "WinRM username. May also be set via WINDOWS_USERNAME.",
				Optional:    true,
			},
			"password": schema.StringAttribute{
				Description: "WinRM password. May also be set via WINDOWS_PASSWORD.",
				Optional:    true,
				Sensitive:   true,
			},
			"use_https": schema.BoolAttribute{
				Description: "Use HTTPS for the WinRM transport (default: false).",
				Optional:    true,
			},
			"insecure": schema.BoolAttribute{
				Description: "Skip TLS certificate verification (default: false). Only useful with use_https=true.",
				Optional:    true,
			},
			"auth_type": schema.StringAttribute{
				Description: "Authentication type: basic, ntlm, or kerberos. Default: ntlm.",
				Optional:    true,
				Validators: []validator.String{
					stringvalidator.OneOf("basic", "ntlm", "kerberos"),
				},
			},
			"timeout": schema.StringAttribute{
				Description: "Operation timeout as a Go duration string (e.g. 30s, 2m). Default: 30s.",
				Optional:    true,
			},
		},
	}
}

// Configure validates the provider configuration, applies environment
// fallbacks, and constructs a shared WinRM client made available to all
// resources and data sources via resp.ResourceData / resp.DataSourceData.
func (p *windowsProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data providerModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if data.Host.IsUnknown() {
		resp.Diagnostics.AddAttributeError(
			pathAttr("host"),
			"Unknown Windows host",
			"The provider cannot create the WinRM client because the host is unknown at plan time.",
		)
	}
	if data.Username.IsUnknown() {
		resp.Diagnostics.AddAttributeError(
			pathAttr("username"),
			"Unknown Windows username",
			"The provider cannot create the WinRM client because the username is unknown at plan time.",
		)
	}
	if data.Password.IsUnknown() {
		resp.Diagnostics.AddAttributeError(
			pathAttr("password"),
			"Unknown Windows password",
			"The provider cannot create the WinRM client because the password is unknown at plan time.",
		)
	}
	if resp.Diagnostics.HasError() {
		return
	}

	cfg := winclient.Config{
		Host:     data.Host.ValueString(),
		Port:     int(data.Port.ValueInt64()),
		Username: data.Username.ValueString(),
		Password: data.Password.ValueString(),
		UseHTTPS: data.UseHTTPS.ValueBool(),
		Insecure: data.Insecure.ValueBool(),
		AuthType: data.AuthType.ValueString(),
	}

	winclient.ResolveFromEnv(&cfg)

	if cfg.Host == "" {
		resp.Diagnostics.AddAttributeError(pathAttr("host"), "Missing Windows host",
			"Set provider attribute 'host' or environment variable WINDOWS_HOST.")
	}
	if cfg.Username == "" {
		resp.Diagnostics.AddAttributeError(pathAttr("username"), "Missing Windows username",
			"Set provider attribute 'username' or environment variable WINDOWS_USERNAME.")
	}
	if cfg.Password == "" {
		resp.Diagnostics.AddAttributeError(pathAttr("password"), "Missing Windows password",
			"Set provider attribute 'password' or environment variable WINDOWS_PASSWORD.")
	}
	if resp.Diagnostics.HasError() {
		return
	}

	timeoutStr := data.Timeout.ValueString()
	if timeoutStr == "" {
		timeoutStr = "30s"
	}
	d, err := time.ParseDuration(timeoutStr)
	if err != nil {
		resp.Diagnostics.AddAttributeError(pathAttr("timeout"), "Invalid timeout",
			fmt.Sprintf("Could not parse duration %q: %s", timeoutStr, err))
		return
	}
	cfg.Timeout = d

	client, err := winclient.New(cfg)
	if err != nil {
		resp.Diagnostics.AddError("Unable to create WinRM client", err.Error())
		return
	}

	resp.ResourceData = client
	resp.DataSourceData = client
}

// Resources returns the set of resources implemented by this provider.
// The list is empty at bootstrap and filled in by follow-up KDust tasks.
func (p *windowsProvider) Resources(_ context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewWindowsServiceResource,
	}
}

// DataSources returns the set of data sources implemented by this provider.
func (p *windowsProvider) DataSources(_ context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{}
}
